-- require("mason").setup({
--   ui = {
--     icons = {
--       package_installed = "✓",
--       package_pending = "➜",
--       package_uninstalled = "✗"
--     }
--   }
-- })
--
-- require("mason-lspconfig").setup()
--
-- require("mason-tool-installer").setup({
--   auto_update = false,
--   run_on_start = true,
-- })
